#ifndef S_CONSTANTS
#define S_CONSTANTS

#define TICK_RATE 120
#define BALL_CURVE_FACTOR 1200
#define BALL_CURVE_INCREASE_RATE 50
#define BALL_CURVE_DECREASE_RATE 0.5
#define BALL_STARTING_SPEED 40
#define BALL_ZVEL_INCREASE_RATE 0.05
#define PADDLE_POS_HISTORY_LENGTH 10

#endif
