#ifndef S_CONSTANTS
#define S_CONSTANTS

#define TICK_RATE 120
#define BALL_CURVE_FACTOR 1200
#define BALL_CURVE_INCREASE_FACTOR 50
#define BALL_CURVE_DECREASE_FACTOR 0.5
#define BALL_STARTING_SPEED 25
#define BALL_ZVEL_INCREASE_FACTOR 0.1

#endif
