#ifndef C_CONSTANTS
#define C_CONSTANTS

#define SERVER_URL "localhost"
#define WEBSOCKET_OPEN 1

#define FPS 0
#define CAMERA_DISTANCE 85
#define CAMERA_FOV 90
#define PADDLE_SPACING 50
#define PADDLE_WIDTH 12
#define PADDLE_HEIGHT 10
#define BALL_RADIUS 2.5
#define BALL_DETAIL 6
#define ARENA_WIDTH 100
#define ARENA_HEIGHT 50
#define ARENA_LENGTH (PADDLE_SPACING * 2)
#define ARENA_SLICES 8

#endif
