#ifndef C_CONSTANTS
#define C_CONSTANTS

#define SERVER_HOSTNAME "localhost"
#define WEBSOCKET_OPEN 1

#define FPS 120
#define CAMERA_DISTANCE 90
#define CAMERA_FOV 90
#define BALL_DETAIL 6
#define ARENA_SLICES 8
#define OUT_OF_BOUNDS 10000
#define PADDLE_FADE_SPEED 0.03
#define PADDLE_MIN_ALPHA 0.2
#define PADDLE_1_COLOR GREEN
#define PADDLE_2_COLOR RED
#define BALL_COLOR GOLD
#define ARENA_COLOR RAYWHITE

#endif
