#ifndef C_CONSTANTS
#define C_CONSTANTS

#define SERVER_HOSTNAME "localhost"
#define WEBSOCKET_OPEN 1

#define FPS 0
#define CAMERA_DISTANCE 90
#define CAMERA_FOV 90
#define BALL_DETAIL 6
#define ARENA_SLICES 8
#define OUT_OF_BOUNDS 10000
#define PADDLE_FADE_SPEED 0.05
#define PADDLE_1_COLOR GREEN
#define PADDLE_2_COLOR RED

#endif
