#ifndef SHARED_CONSTANTS_H
#define SHARED_CONSTANTS_H

#define PADDLE_SPACING 50
#define PADDLE_WIDTH 16
#define PADDLE_HEIGHT 12
#define BALL_RADIUS 3
#define ARENA_LENGTH (PADDLE_SPACING * 2)
#define ARENA_WIDTH 100
#define ARENA_HEIGHT 70

typedef enum MESSAGE_TYPE {
    MSG_TYPE_SEND_PADDLE = 0,
    MSG_TYPE_SEND_BALL,
    MSG_TYPE_ASSIGN_SIDE,
    MSG_TYPE_PADDLE_DISCONNECT,
    MSG_TYPE_PADDLE_HIT_BALL
} MESSAGE_TYPE;

typedef enum PADDLE_SIDE {
    SIDE_UNASSIGNED = 0,
    SIDE_1,
    SIDE_2
} PADDLE_SIDE;


#endif
