#ifndef SHARED_CONSTANTS_H
#define SHARED_CONSTANTS_H

#define SEND_PADDLE_PLAYER_1 1
#define SEND_PADDLE_PLAYER_2 2
#define SEND_BALL 3
#define ASSIGN_SIDE_1 4
#define ASSIGN_SIDE_2 5

#define PADDLE_SPACING 50
#define ARENA_LENGTH (PADDLE_SPACING * 2)
#define ARENA_WIDTH 100
#define ARENA_HEIGHT 50

#endif
